CREATE TABLE TIPO(
Tipo_ID Int PRIMARY KEY,
Tipo_Nome Text,
);

CREATE TABLE FRAQUEZAS(
Tipo_ID Int NOT NULL PRIMARY KEY,
Fraqueza_1_ID INT NOT NULL,
Fraqueza_2_ID INT,
Fraqueza_3_ID INT,
Fraqueza_4_ID INT,
Fraqueza_5_ID INT,
CONSTRAINT FK_TIPO_ID FOREIGN KEY(Tipo_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_FRAQUEZA_1_ID FOREIGN KEY(Fraqueza_1_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_FRAQUEZA_2_ID FOREIGN KEY(Fraqueza_2_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_FRAQUEZA_3_ID FOREIGN KEY(Fraqueza_3_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_FRAQUEZA_4_ID FOREIGN KEY(Fraqueza_4_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_FRAQUEZA_5_ID FOREIGN KEY(Fraqueza_5_ID) REFERENCES TIPO(TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE EFEITO (
Efeito_ID Int PRIMARY KEY,
Efeito_Nome Text,
Efeito_Info Text NOT NULL
);

CREATE TABLE HABILIDADE(
Habilidade_ID Int PRIMARY KEY,
Habilidade_Tipo Int, 
Habilidade_Nome Text,
Habilidade_Descricao Text NOT NULL,
Habilidade_Efeito Int, 
CONSTRAINT FK_TIPO FOREIGN KEY (Habilidade_Tipo) REFERENCES TIPO(Tipo_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_EFEITO FOREIGN KEY (Habilidade_Efeito) REFERENCES EFEITO(Efeito_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE POKEDEX(
Pokedex_Num INT PRIMARY KEY,
Pokedex_Nome Text NOT NULL,
Pokedex_Tipo_1 Int NOT NULL,
Pokedex_Tipo_2 Int,
Pokedex_Taxa_Captura Float NOT NULL,
Pokedex_Geracao Int NOT NULL,
Pokedex_Info Text NOT NULL,
Pokedex_Capturado Boolean NOT NULL DEFAULT FALSE,
CONSTRAINT POKEMON_NOME_UNICO UNIQUE (Pokedex_Nome),
CONSTRAINT FK_TIPO_1 FOREIGN KEY (Pokedex_Tipo_1) REFERENCES TIPO (TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_TIPO_2 FOREIGN KEY (Pokedex_Tipo_2) REFERENCES TIPO (TIPO_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT CHECK_TAXA_CAPTURA CHECK (Pokedex_Taxa_Captura >=0 AND Pokedex_Taxa_Captura <=100),
CONSTRAINT CHECK_GERACAO CHECK (Pokedex_Geracao > 0 AND Pokedex_Geracao < 10)
);

CREATE TABLE EVOLUCAO(
Anterior Int,
Sucessor Int, 
PRIMARY KEY (Anterior, Sucessor),
CONSTRAINT FK_ANTERIOR FOREIGN KEY (Anterior) REFERENCES POKEDEX(Pokedex_Num) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_SUCESSOR FOREIGN KEY (SUCESSOR) REFERENCES POKEDEX(Pokedex_Num) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE POKEMON(
Pokemon_ID Int PRIMARY KEY,
Pokemon_Nome Text NOT NULL,
Pokemon_Habilidade_1 Int NOT NULL,
Pokemon_Habilidade_2 Int,
Pokemon_Habilidade_3 Int,
Pokemon_Habilidade_4 Int,
Pokemon_Level_MIN Int NOT NULL DEFAULT 1,
Pokemon_Level_MAX Int NOT NULL DEFAULT 100,
Pokemon_HP_MIN INT NOT NULL,
Pokemon_HP_MAX INT NOT NULL,
Pokemon_ATK_MIN INT NOT NULL,
Pokemon_ATK_MAX INT NOT NULL,
Pokemon_DEF_MIN INT NOT NULL,
Pokemon_DEF_MAX INT NOT NULL,
Pokemon_SP_ATK_MIN INT NOT NULL,
Pokemon_SP_ATK_MAX INT NOT NULL,
Pokemon_SP_DEF_MIN INT NOT NULL,
Pokemon_SP_DEF_MAX INT NOT NULL,
Pokemon_VELOCIDADE_MIN INT NOT NULL,
Pokemon_VELOCIDADE_MAX INT NOT NULL,
Pokemon_Sexo Char NOT NULL,
Pokemon_Altura Float NOT NULL,
Pokemon_Peso Float NOT NULL,
Pokemon_IMG Text NOT NULL,
CONSTRAINT FK_POKEMON_ID FOREIGN KEY (Pokemon_ID) REFERENCES POKEDEX(POKEDEX_NUM) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_POKEMON_HABILIDADE_1 FOREIGN KEY (Pokemon_Habilidade_1) REFERENCES HABILIDADE(HABILIDADE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_POKEMON_HABILIDADE_2 FOREIGN KEY (Pokemon_Habilidade_2) REFERENCES HABILIDADE(HABILIDADE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_POKEMON_HABILIDADE_3 FOREIGN KEY (Pokemon_Habilidade_3) REFERENCES HABILIDADE(HABILIDADE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_POKEMON_HABILIDADE_4 FOREIGN KEY (Pokemon_Habilidade_4) REFERENCES HABILIDADE(HABILIDADE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT CHECK_LEVEL CHECK(Pokemon_Level_MIN > 0 AND Pokemon_Level_MAX <= 100),
CONSTRAINT CHECK_STATS CHECK(Pokemon_HP_MIN > 0 AND Pokemon_HP_MAX > 0 AND Pokemon_ATK_MIN > 0 AND Pokemon_ATK_MAX > 0 AND Pokemon_DEF_MIN > 0 AND Pokemon_DEF_MAX > 0 
AND Pokemon_SP_ATK_MIN > 0 AND Pokemon_SP_ATK_MAX > 0 AND Pokemon_SP_DEF_MIN > 0 AND Pokemon_SP_DEF_MAX > 0 AND Pokemon_VELOCIDADE_MIN > 0 AND Pokemon_VELOCIDADE_MAX > 0),
CONSTRAINT CHECK_SEXO CHECK(Pokemon_Sexo = 'M' OR Pokemon_Sexo = 'F'),
CONSTRAINT CHECK_ALTURA CHECK(Pokemon_Altura > 0),
CONSTRAINT CHECK_PESO CHECK(Pokemon_Peso > 0)
);

CREATE TABLE TREINADOR(
Treinador_ID Int PRIMARY KEY,
Treinador_Nome Text NOT NULL
);

CREATE TABLE REGISTRO_POKEDEX(
Pokemon_ID Int PRIMARY KEY,
Treinador_ID Int NOT NULL DEFAULT 1,
Pokemon_Data_Captura Date,
Pokemon_Hp INT,
Pokemon_Atk INT,
Pokemon_Def INT,
Pokemon_SP_Atk INT,
Pokemon_SP_Def INT,
Pokemon_Velocidade INT,
Pokemon_Level INT,
CONSTRAINT FK_POKEMON_ID FOREIGN KEY(Pokemon_ID) REFERENCES POKEDEX(POKEDEX_NUM) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT FK_TREINADOR_ID FOREIGN KEY(Treinador_ID) REFERENCES TREINADOR(TREINADOR_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

--Tabela para arquivo de capturados e arquivo PDF
CREATE TABLE CAPTURADOS_LOG(
Treinador_Nome Text,
Pokemon_Nome Text,
Data_Captura Date,
Hora_Captura Time
);

--Tabela usada como arquivo log
CREATE TABLE ADMIN_LOG (
    Id SERIAL PRIMARY KEY,
    Operacao text,
    Nome_tabela text,
    Data_Captura TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
