CREATE TABLE TIPO(
Tipo_Nome Text PRIMARY KEY,
Cor Text NOT NULL
);

CREATE TABLE FRAQUEZAS(
Fraquezas_Nome Text NOT NULL,
Fraquezas_Tipo_Nome Text REFERENCES TIPO(Tipo_Nome),
PRIMARY KEY (Fraquezas_Nome, Fraquezas_Tipo_Nome)
);

CREATE TABLE EFEITO (
Efeito_Nome Text PRIMARY KEY,
Efeito_Info Text NOT NULL
);

CREATE TABLE HABILIDADE(
Habilidade_Nome Text PRIMARY KEY,
Habilidade_Tipo Text REFERENCES TIPO(Tipo_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Habilidade_Descricao Text NOT NULL,
Habilidade_Efeito Text REFERENCES EFEITO(Efeito_Nome) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE POKEDEX(
Pokedex_Num INT PRIMARY KEY,
Pokedex_Nome Text NOT NULL,
Pokedex_Tipo_1 Text NOT NULL REFERENCES TIPO(Tipo_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokedex_Tipo_2 Text REFERENCES TIPO(Tipo_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokedex_Taxa_Captura Float CHECK(Pokedex_Taxa_Captura >= 0 AND Pokedex_Taxa_Captura <=100),
Pokedex_Info Text NOT NULL
);

CREATE TABLE EVOLUCAO(
Anterior Int REFERENCES POKEDEX(Pokedex_Num) ON DELETE RESTRICT ON UPDATE CASCADE,
Sucessor Int REFERENCES POKEDEX(Pokedex_Num) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (Anterior, Sucessor)
);

CREATE TABLE POKEMON(
Pokemon_ID Int PRIMARY KEY REFERENCES POKEDEX(Pokedex_Num) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokemon_Nome Text NOT NULL,
Pokemon_Habilidade_1 Text NOT NULL REFERENCES HABILIDADE(Habilidade_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokemon_Habilidade_2 Text REFERENCES HABILIDADE(Habilidade_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokemon_Habilidade_3 Text REFERENCES HABILIDADE(Habilidade_Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
Pokemon_Habilidade_4 Text REFERENCES HABILIDADE(Habilidade_Nome) ON DELETE RESTRICT ON UPDATE CASCADE
)
